### ISSUE TITLE
WARN[10800] APRS-IS is not connected and not configured. Verify config

### ISSUE THREAD

**Issue by mathisono** [cceremuga/ionosphere#10]
INFO[10800] Uploading beacon.                            
WARN[10800] APRS-IS is not connected and not configured. Verify config.

What am I missing that's causing the WARN?

config
-------------------------
beacon:
  enabled: true
  call-sign: "KJ6DZB-5"
  interval: 10m
  comment: "145.825mhz RX"

handlers:
- id: "4967ade5-7a97-416f-86bf-6e2ae8a5e581"
  name: "stdout"
- id: "b67ac5d5-3612-4618-88a9-a63d36a1777c"
  name: "aprsis"
  options:
    enabled: true
    server: "noam.aprs2.net:14580"
    call-sign: "kj6dzb"
    passcode: "XXXXX"
    filter: ""
-------------------------------

BTW works great!

**Comment by cceremuga** [comment]
I'll step through it using a similar config and see where we end up. The TCP/IP connection handling I wrote is possibly a bit brittle and it could be a situation where it's disconnected and not correctly reporting.

When you get these warnings have you been able to verify whether or not the spots are making it to APRS-IS anyway? You can usually verify this by going to the address of the server in question and seeing your host on the list if it's connected.

**Comment by cceremuga** [comment]
I've added some additional debugging to the latest beta branch. In the event this crops up again, we can get some logs.
