### ISSUE TITLE
Please explain how to install ionosphere onto RPI

### ISSUE THREAD

**Issue by dima72** [cceremuga/ionosphere#11]
subj

**Comment by cceremuga** [comment]
Sure thing, I'll be setting up an updated RPI test environment soon-ish and will add additional into to the README.

**Comment by g7gpr** [comment]
This repository 

https://github.com/g7gpr/rpiionosphereinstaller

contains a script which may be helpful. @cceremuga , can you cast your eye over it?

**Comment by cceremuga** [comment]
This is awesome. I'm gonna link to your repo in the README for the next beta thank you!
