### ISSUE TITLE
Exit on startup wit error: Failed to initialize log file

### ISSUE THREAD

**Issue by geolimber** [cceremuga/ionosphere#12]
Can't launch program. It exits with this message:
```
FATA[0000] Failed to initialize log file.
exit status 1
```

**Comment by g7gpr** [comment]
Hi, I have a workaround for this

In your ionosphere directory make a logs directory

mkdir logs

depending on how you have set up your directory structure you may need

sudo mkdir logs

cceremuga - do you welcome pull requests - is there any particular branch you prefer them to be submitted on?

**Comment by cceremuga** [comment]
@g7gpr master is just fine! i'll make sure it gets out in a patch release.

**Comment by cceremuga** [comment]
I've got a `beta2` branch pushing up shortly which has a fix for this in the Makefile. Until that's released, @g7gpr's workaround should be effective.

**Comment by g7gpr** [comment]
That's a neat way of doing it. I'll give it a test when it lands.

**Comment by cceremuga** [comment]
Build in latest beta2 branch will add a placeholder to the logs directory to resolve this
