### ISSUE TITLE
Location in the beacon message?

### ISSUE THREAD

**Issue by hardlifeofapo** [cceremuga/ionosphere#14]
Hi,

Let me begin with a big thank-you for creating this. Much appreciated!

I've been taking a look at the structure of the beacon, and it seems that all the elements of the go-aprs packet are available. 

Would it be possible to include location in the beacon uploaded to APRS-IS?

I'm not a go developer, but I take take a first stab at it if you can provide some support.

Thanks,
Pablo

**Comment by gmccabe** [comment]
It currently works as-is if you use the comment string in line 18 of the config.

APRS format example is !DDMM.hhN/DDDMM.hhW$comments

**Comment by ve6cgn** [comment]
I have a station set up with ionosphere and an rtl dongle. it's recieving, but not appearing on the map.. (aprs.fi).  I followed the format, but nothing..  (comment: "!5324.97N/11332.08W$Ionosphere RTL-SDR I-Gate")

Am I missing something?

**Comment by gmccabe** [comment]
The APRS format is defined here http://www.aprs.net/vm/DOS/PROTOCOL.HTM. Based on your string, the symbol you are transmitting is defined by the / and & characters. You can change the symbol by using the appropriate characters for the symbols defined here http://www.aprs.org/symbols.html.

**Comment by hardlifeofapo** [comment]
Confirmed this works. Changing $ for - makes the house icon appear.

**Comment by cceremuga** [comment]
Going to add these details to the `README` to ensure it's clearer in the next release. Thank you both!
