### ISSUE TITLE
application exits as soon as it states "Listening for packets"

### ISSUE THREAD

**Issue by ve6cgn** [cceremuga/ionosphere#17]
I'm trying to run ionosphere on an older netbook running Ubuntu server (Latest release, command line only).  Everything loads properly when I issue the ./ionosphere command, but instead of listening for packets, the program terminates, and I am back at the curser.  The log file is completely empty.

Is there some dependacy that I'm missing, running on a non Gui version of Linux?  

update: I was able to get it running properly installing it a different way (apt install).  so likely there was a dependency that wasn't being fulfilled.

**Comment by cceremuga** [comment]
Sweet, glad you were able to get it working. I'll try and write up some clearer docs in the `README` that should make the setup steps a bit more straightforward.
