### ISSUE TITLE
[Feature Request] Add location to beacons

### ISSUE THREAD

**Issue by Vertikar** [cceremuga/ionosphere#20]
Would be great to be able to specify a fixed location in a beacon, similar to what Direwolf allows.
Ideally would be awesome to be able to feed it from GPSD in the future.

**Comment by DGxInfinitY** [comment]
Would be super useful. Even just allowing the option to add latitude and longitude to the config.yaml for static beacons. Also, it would be nice to add status comments as well. This is the only thing holding me back from using this full-time in a production setting. It is amazing to be able to do so much already but just this little addition would get this project going in a direction where more help would be available to help build a plugin framework.

**Comment by cceremuga** [comment]
Gonna link this to the other enhancement for the same request and close this one, thanks!
